wildflower-keeper/frontend

- src/app/page.tsx
- src/components/dashboardItems/AdminInfoContainer/index.tsx
- src/components/dashboardItems/DashboardBody/index.tsx
> 핫픽스 첫화면 에러 해결

- src/components/InputWithLabel/index.tsx
- src/components/base/CustomSelectBox/index.tsx
- src/components/dashboardItems/AdminInfoContainer/DateInfo/index.tsx
- src/components/dashboardItems/ManagementContainer/index.tsx
- src/components/dashboardItems/UserBoardContainer/PagenationButtonContainer/index.tsx
- src/components/dashboardItems/UserBoardContainer/UserBoard/index.tsx
- src/components/dashboardItems/UserBoardContainer/UserBoardItem/index.tsx
- src/components/dashboardItems/UserBoardContainer/index.tsx
- src/components/dashboardItems/UserBoardHeader/index.tsx
- src/components/ui/LoginForm/index.tsx
- src/utils/common.ts
- src/utils/pagenation.ts
- 로그인 화면 디자인 변경
- 페이지네이션 기능 구현
- 린트 에러 해결
|기능|스크린샷|
|---|---|
|||
> 페이지네이션, 로그인 디자인

- src/components/dashboardItems/AdminInfoContainer/ManagerInfo/index.tsx
- src/utils/common.ts
- 당직자가 없을 시 화면이 나오지 않는 문제 긴급 해결
|기능|스크린샷|
|---|---|
|||
> 당직자가 없을 시 화면이 나오지 않는 문제 긴급 해결

- src/components/InputWithLabel/index.tsx
- src/components/base/CustomSelectBox/index.tsx
- src/components/client/Login.page.tsx
- src/components/dashboardItems/AdminInfoContainer/DateInfo/index.tsx
- src/components/dashboardItems/AdminInfoContainer/index.tsx
- src/components/dashboardItems/DashboardHeader/index.tsx
- src/components/dashboardItems/ManagementContainer/index.tsx
- src/components/dashboardItems/UserBoardContainer/SearchInput/index.tsx
- src/components/dashboardItems/UserBoardContainer/SearchSelector/index.tsx
- src/components/dashboardItems/UserBoardContainer/StatusBadge/index.tsx
- src/components/dashboardItems/UserBoardContainer/UserBoard/index.tsx
- src/components/dashboardItems/UserBoardContainer/UserBoardItem/index.tsx
- src/components/dashboardItems/UserBoardContainer/index.tsx
- src/components/dashboardItems/UserBoardHeader/index.tsx
- src/components/dashboardItems/UserCurrentSituation/CurrentCardContainer/index.tsx
- src/components/ui/LoginForm/index.tsx
- src/store/useUpdateTimer.ts
- src/utils/date/date.ts
- yarn.lock
> 디자인 변경 기능 추가

- src/components/dashboardItems/ManagementContainer/index.tsx
- src/components/dashboardItems/MonthlyReport/index.tsx
- src/components/dashboardItems/ProgressContainer/index.tsx
> progress bar 생성

- src/components/Map/index.tsx
- src/components/dashboardItems/EmergencyContainer/index.tsx
지도 마커 추가
|기능|스크린샷|
|---|---|
|||
> 지도 사용 확인을 위한 배포

- src/components/dashboardItems/ManagementContainer/index.tsx
- src/components/ui/LoginForm/index.tsx
> 비밀번호 찾기 버튼 제거

- src/components/dashboardItems/DashboardBody/index.tsx
- src/components/dashboardItems/DashboardHeader/index.tsx
- src/components/dashboardItems/DashboardSideBar/index.tsx
- src/components/ui/DashboardContainer/index.tsx
- src/utils/api/axios.ts
- 화면 width에 맞게 레이아웃이 변하도록 수정
- Query-String으로 대시보드 타입 변경하도록 수정
|기능|스크린샷|
|---|---|
|||
> 레이아웃 퍼블리싱, Query-String 설계

- src/components/dashboardItems/DashboardHeader/index.tsx
- 디자인 변경으로 헤더에 이름이 변경되는 기능이 사라짐에 따라 헤더 이름을 담아둔 객체 제거
- 디자인 변경으로 헤더에 이름이 변경되는 기능이 사라짐에 따라 헤더 이름을 담아둔 객체 제거
|기능|스크린샷|
|---|---|
|||
> 사용하지 않는 상수 객체 제거

- src/components/ui/DashboardContainer/index.tsx
- useSearchParams사용하는 태그 상위에 Suspense태그 적용 
- app폴더 내부에 있던constants폴더와 hooks폴더를 src폴더로 이동
|기능|스크린샷|
|---|---|
|||
> Suspense태그 적용, constants폴더와 hooks폴더 이동

- src/components/ui/DashboardContainer/index.tsx
Reverts wildflower-keeper/frontend#30
> Revert "Suspense태그 적용, constants폴더와 hooks폴더 이동"

- src/components/dashboardItems/DashboardHeader/index.tsx
Reverts wildflower-keeper/frontend#29
> Revert "사용하지 않는 상수 객체 제거"

- src/components/dashboardItems/DashboardBody/index.tsx
- src/components/dashboardItems/DashboardHeader/index.tsx
- src/components/dashboardItems/DashboardSideBar/index.tsx
- src/components/ui/DashboardContainer/index.tsx
- src/utils/api/axios.ts
Reverts wildflower-keeper/frontend#28
> Revert "레이아웃 퍼블리싱, Query-String 설계"

- src/components/dashboardItems/DashboardHeader/index.tsx
- src/components/ui/DashboardContainer/index.tsx
- 로그아웃 기능 구현
|기능|스크린샷|
|---|---|
|||
> 로그아웃 기능 구현

- src/api/v1/shelter-admin/index.ts
- src/components/Layout/LoginForm/index.tsx
- 로그인 화면에서 패스워드를 잘못 입력했을 때 경고 메시지 출력
|기능|스크린샷|
|---|---|
||![image](https://github.com/user-attachments/assets/c603c35a-2ff0-4035-9dba-8c112dca702c)|
> 패스워드 오류 경고 메시지 추가

- src/components/Layout/AddUserForm/index.tsx
- src/components/List/UserBoard/items/UserBoardItem.tsx
- 아직 사용자 추가 부분이 명확하게 정해지지 않아서 배포 이후 임시적으로 사용자 추가 기능을 사용할 수 있도록 수정했습니다.
|기능|스크린샷|
|---|---|
|||
> 사용자 추가시 임시 데이터와 함께 추가

- src/api/v1/shelter-admin/index.ts
- src/components/Layout/AddUserForm/index.tsx
> 빌드 에러 수정 > 타입 참조 중복

- src/components/Layout/AfterLoginLayouts/index.const.ts
- 공지사항 페이지 구현 전이기 때문에 숨김처리
|기능|스크린샷|
|---|---|
|||
> 사이드바에서 공지사항 숨김 처리

- src/components/Composition/UserListFilter/index.tsx
- src/components/Layout/UserBoardContainer/index.tsx
- 필터 적용 시 페이지가 초기화 되도록 설정
|기능|스크린샷|
|---|---|
|||
> 필터링 시 페이지 1로 수정

- src/components/Composition/LogoutButton/index.tsx
- [ x] 새로운 기능 추가
- 로그아웃 시 모든 캐시 데이터 삭제(보안 강화)
|기능|스크린샷|
|---|---|
|||
> 로그아웃시 모든 캐시 삭제

- src/components/Chart/UserStatusChart/generateData.tsx
- src/components/Chart/UserStatusChart/index.tsx
> 차트 데이터가 로드되기 전에는 차트를 보여주지 않음

- src/api/v1/shelter-admin/index.ts
- src/api/v1/shelter-admin/type.d.ts
- src/api/v2/shelter-admin/index.ts
- src/api/v2/shelter-admin/type.d.ts
- src/components/Composition/SearchBar/items/SearchInput.tsx
- src/components/Layout/AddNoticeForm/index.tsx
- src/components/Layout/AddNoticeForm/items/NoticePreview.tsx
- src/components/Layout/AddNoticeForm/items/NotificationTypeSelector.tsx
- src/components/Layout/AddNoticeForm/items/OpenSelectUserButton.tsx
- src/components/Layout/AddNoticeForm/items/SelectedUserList.tsx
- src/components/Layout/AddUserForm/index.tsx
- src/components/Layout/AfterLoginLayouts/SideBar.tsx
- src/components/Layout/NoticeContainer/index.tsx
- src/components/Layout/NoticeContainer/items/Notice.tsx
- src/components/Layout/NoticeContainer/items/NoticeHeader.tsx
- src/components/Layout/NoticeContainer/items/NoticeList.tsx
- src/components/Layout/NoticeContainer/items/SuccessPopup.tsx
- src/components/Layout/NoticeProvider/index.tsx
- src/components/Layout/NoticeRecipientModal/index.tsx
- src/components/Layout/NoticeRecipientModal/items/SelectedUserList.tsx
- src/components/Layout/NoticeRecipientModal/items/UserList.tsx
- src/components/Layout/NoticeRecipientModal/items/UserListContainer.tsx
- src/components/Layout/NoticeRecipientModal/items/UserListHeader.tsx
- src/components/Layout/UserBoardContainer/index.tsx
- src/components/List/UserBoard/items/StatusControllerOpenToggle.tsx
- src/components/base/CloseButton/index.tsx
> Feature/spt 49 공지사항 전송 기능

- src/api/v1/shelter-admin/type.d.ts
- src/components/Composition/SearchBar/items/SearchInput.tsx
- src/components/Layout/NoticeRecipientModal/items/UserListContainer.tsx
- src/components/Layout/UserBoardContainer/index.tsx
- src/hooks/useSearch.tsx
- 빈 칸으로 유저 이름 검색 시 전체 검색
- 유저 태그 필터링 버그 수정
|기능|스크린샷|
|---|---|
|||
> Feature/spt 63 

- src/components/Layout/AddNoticeForm/items/AddText.tsx
- src/components/Layout/AddNoticeForm/items/FinalCheckButton.tsx
- src/components/Layout/AddNoticeForm/items/SelectedUserList.tsx
- src/components/Layout/NoticeProvider/index.tsx
- src/components/Layout/NoticeRecipientModal/items/UserList.tsx
- 공지사항 전송 성공 시 선택 유저 초기화
- 공지사항 개별전송 유저명 최대 4글자까지 보임
|기능|스크린샷|
|---|---|
|||
> 공지사항 개별전송 유저명 overflow-hidden & 전송 성공 시 선택 유저 초기화

- src/components/Layout/AddNoticeForm/items/AddText.tsx
> 개별전송 유저 미선택 시 전송 disable처리

- src/components/Layout/SecondAuth/index.tsx
> 이메일 인증코드 입력 가능시간 3분 -> 5분

- src/components/Layout/AddNoticeForm/items/AddText.tsx
- src/components/Layout/SecondAuth/index.tsx
> 로그인 가능 시간 180초 > 300초 & 공지사항 내용 최대 50자 > 100자

- src/components/Layout/NoticeDetail/index.tsx
- src/components/Layout/NoticeDetail/items/RecipientList.tsx
> 공지사항 상세이력 버튼 위치 수정

- src/components/Composition/UserManagementButtonContainer/index.tsx
> 유저 삭제 버튼 복구
